name: Build

on:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Login to docker hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: |
            tuxnvape/openarena-arm:latest
            tuxnvape/openarena-arm:arm32

      - name: Build and push 64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile64
          platforms: linux/arm64
          push: true
          tags: |
            tuxnvape/openarena-arm:arm64
